# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 08:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lottery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('nb_of_odds', models.IntegerField(null=True)),
                ('flag_for_odds', models.BooleanField(default=False)),
                ('timing', models.IntegerField()),
                ('nb_0f_b20', models.IntegerField(null=True)),
                ('flag_for_b20', models.BooleanField(default=False)),
                ('score_range_top', models.IntegerField(null=True)),
                ('score_range_bottom', models.IntegerField(null=True)),
                ('flag_for_score', models.BooleanField(default=False)),
                ('set_score', models.IntegerField()),
                ('prev_rep_nb', models.IntegerField(null=True)),
                ('flag_for_prev_rep', models.BooleanField(default=False)),
                ('nb_to_Inc', models.CharField(max_length=50)),
                ('nb_of_games', models.IntegerField()),
                ('failed_flag', models.BooleanField(default=False)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.Lottery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
